### ISSUE TITLE
Don't hardcode path to `SVcomp.pl` in `SVfindmatches.pl`

### ISSUE THREAD

**Issue by ifiddes-10x-zz** [nhansen/SVanalyzer#1]
https://github.com/nhansen/SVanalyzer/blob/master/scripts/SVfindmatches.pl#L81

**Comment by nhansen** [comment]
Hi Ian,
I've reworked the code for SVanalyzer extensively, and condensed its functionality into five use cases:
SVmerge - merge equivalent SVs in one or more VCF files
SVcomp - pairs of structural variants (same as previously)
SVbenchmark - compare one "test" VCF file to a "truth" VCF file and report precision, recall, f1
SVwiden - characterize structural variants as to similarity at their breakpoints, and thus ambiguity in their positioning
SVrefine - call repeat-aware structural variants from assembly alignments (also same as previous versions)

Documentation is at http://svanalyzer.readthedocs.io/en/latest/, and code is considerably cleaner than before. Please give it a try at your convenience!
