### ISSUE TITLE
delta2sam.pl

### ISSUE THREAD

**Issue by Yutang-ETH** [nhansen/SVanalyzer#13]
Hi Nancy,

My name is Yutang and I am a PhD student at ETH, Zurich. I saw your comment here https://github.com/mummer4/mummer/issues/130, and I have tried your delta2sam.pl script. It worked like a charm but when I try to convert sam to bam, an error came up saying [W::sam_read1_sam] Parse error at line 4. I guess there might be something wrong in the sam file, what do you think?

Attached is part of my sam file and could you please have a look? 

Thank you very much for your help and I am looking forward to your reply.

Best wishes,
Yutang
[test.txt](https://github.com/nhansen/SVanalyzer/files/7927425/test.txt)

**Comment by nhansen** [comment]
Hi Yutang,
Thanks for pointing this out. I had only tested the SAM format on old versions of samtools. I've corrected the problem (I was printing * characters in the PNEXT and TLEN fields, which now only accept integers). The new version of the script is at https://raw.githubusercontent.com/nhansen/SVanalyzer/master/scripts/misc/delta2sam.pl
If you wouldn't mind giving it a try and letting me know if it corrects the problem, I'd be grateful.
Best wishes,
--Nancy

**Comment by Yutang-ETH** [comment]
Hi Nancy,

Thank you very much for your very quick response and action.  I just tested the new script, now it works perfectly! I could convert sam to bam by samtools. Thank you really much.

By the way, how should I cite this tool? 

Best wishes,
Yutang

**Comment by nhansen** [comment]
Thanks, Yutang!

You can cite the delta2sam script as part of the SVanalyzer toolkit with the GitHub address https://github.com/nhansen/SVanalyzer, or if you want to cite a publication, it would be appropriate to use: 

Zook, Justin M., Nancy F. Hansen, Nathan D. Olson, Lesley Chapman, James C. Mullikin, Chunlin Xiao, Stephen Sherry, et al. “A Robust Benchmark for Detection of Germline Large Deletions and Insertions.” Nature Biotechnology 38, no. 11 (November 2020): 1347–55. https://doi.org/10.1038/s41587-020-0538-8.

**Comment by Yutang-ETH** [comment]
Wonderful, Nancy! Thanks again for your help.

Best wishes,
Yutang
