### ISSUE TITLE
Conda installation command in README.md not working

### ISSUE THREAD

**Issue by yueyaog** [nhansen/SVanalyzer#17]
I tried to install SVanalyzer using the `conda install svanalyzer` command as specified in the README.md file. However, I received the following error message:
```
PackagesNotFoundError: The following packages are not available from current channels:
- svanalyzer
```
After some research, I found that the correct command to install SVanalyzer using conda is `conda install -c bioconda svanalyzer`.

I suggest updating the README.md file to reflect this change in the installation command, as it can save others from experiencing the same issue.

Thank you for maintaining this svanalyzer.

**Comment by nhansen** [comment]
Thanks so much for pointing this out! Yes, if you don't have bioconda specified as a default channel in your .condarc file, you'll need to use the -c bioconda option when installing with conda. I've updated the README to reflect this.
