### ISSUE TITLE
Can't locate GTB/File.pm

### ISSUE THREAD

**Issue by Cauwth** [nhansen/SVanalyzer#19]
In Ubuntu22.04,when using svanalyzer,it reported:
`Can't locate GTB/File.pm in @INC (you may need to install the GTB::File module) `
I tried `cpan GTB::File` and `cpanm GTB::File`.But `! Couldn't find module or a distribution GTB::File`
how can i get it??
thank u

**Comment by nhansen** [comment]
Did you  install using conda or the instructions under "Building github version on your own"? The GTB::File module is included with the distribution in this repository. It sounds like SVanalyzer isn't installed correctly

**Comment by Cauwth** [comment]
thank you.add `PERL5LIB="/home/user/miniconda3/envs/svanalyzer/lib/site_perl/5.26.2:/home/user/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;` to `~/.bashrc` can solve this.
