### ISSUE TITLE
how to ilter SV with 1000bp？

### ISSUE THREAD

**Issue by Flooooooooooooower** [nhansen/SVanalyzer#22]
Hi there,
I have read this paper (A robust benchmark for detection of germline large deletions and insertions), but some questions confused me as follows. When I use SVmerge to merge different VCF files, how should I filter out another SV within 1000bp? Maybe Bcftools could do this ?  or you haven't provided a script, but you've just provided an idea?
Thank you in advance for helping me with my confusion.
best wishes
Flooooooooooooower

**Comment by nhansen** [comment]
Hi! I'm not sure I understand the question. SVmerge will merge nearby variants if it considers them to be similar enough (essentially, if the sequence produced by applying each variant to the reference is roughly the same) but it won't if they are two different variants (even if they're within 1kb of each other). Why do you want to filter out nearby variants?
