### ISSUE TITLE
./Build test failure

### ISSUE THREAD

**Issue by Mkddb** [nhansen/SVanalyzer#6]
Thanks nhansen..
For creating such a useful tool.

I am getting this error during installation in the building step.
when i enter this command..
**./Build test**

i am receiving this message.. please check if this is an error. if it can be skipped or fixed.

t/1_load.t .. ok     
t/2_call.t .. 1/16 
#   Failed test 'blib/script/SVwiden vartype'
#   at t/2_call.t line 47.
#                   ''
#     doesn't match '(?^:REPTYPE=DUP)'

#   Failed test 'blib/script/SVwiden widensmall'
#   at t/2_call.t line 49.
#                   ''
#     doesn't match '(?^:REFWIDENED=1:842056-842090)'
t/2_call.t .. 14/16 # Looks like you failed 2 tests of 16.
t/2_call.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/16 subtests 

Test Summary Report
-------------------
t/2_call.t (Wstat: 512 Tests: 16 Failed: 2)
  Failed tests:  5-6
  Non-zero exit status: 2
Files=2, Tests=38,  6 wallclock secs ( 0.04 usr  0.01 sys +  4.84 cusr  0.70 csys =  5.59 CPU)
Result: FAIL
Failed 1/2 test programs. 2/38 subtests failed.

Thanks in advance.

**Comment by nhansen** [comment]
Thanks for letting me know about this. Can you post the contents of the file t/test2.out in your SVanalyzer directory?

**Comment by Mkddb** [comment]
Yes,

The content in file t/test2.out says..
**Can't open t//nucmer.prefix.delta, No such file or directory**

While, there is another file as "nucmer.prefix.err" which has the following content..
**nucmer: error while loading shared libraries: libumdmummer.so.0: cannot open shared object file: No such file or directory**

am i missing some paths or some files itself ?

**Comment by nhansen** [comment]
It looks to me like there's a problem with your nucmer installation, then. Solution is to find that shared library file. Until then, all tools in SVanalyzer should work *except* for SVwiden, which uses nucmer to find widened coordinates of variants.
